---
abstract: 'web crawler'
author:
  - 'Peter Karman, C<< <karman at cpan.org> >>'
build_requires:
  DBD::SQLite: 0
  ExtUtils::MakeMaker: 6.59
  HTTP::Server::Simple: 0
  Test::HTTP::Server::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: http://dev.perl.org/licenses/
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dezi-Bot
no_index:
  directory:
    - inc
    - t
requires:
  CHI: 0
  DBIx::Connector: 0
  DBIx::InsertHash: 0
  Data::Dump: 0
  Digest::MD5: 0
  File::Temp: 0
  Module::Load: 0
  Parallel::Prefork: 0
  SWISH::Prog: 0.67
  Test::More: 0
  Time::HiRes: 0
  perl: 5.8.9
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Dezi-Bot
  homepage: https://github.com/karpet/dezi-bot
  license: http://opensource.org/licenses/gpl-license.php
  repository: http://github.com/karpet/dezi-bot
version: 0.001
